nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api':
            allow_origin: ['http://localhost:8080/']
            allow_headers: ['Content-Type, Accept, Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600
